name: Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag blog:$(date +%s)

  test:
      runs-on: ubuntu-latest
      env:
        PORT: 8000
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Set up JDK 16
          uses: actions/setup-java@v2
          with:
            java-version: '16'
            distribution: 'adopt'
        - name: Test with Gradle

          run: gradle clean build

  deploy:
      runs-on: ubuntu-latest
      needs: [test]
      
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Deploy a Docker container to Heroku.
          uses: gonuit/heroku-docker-deploy@v1.3.3
          with:
            email: ${{ secrets.HEROKU_EMAIL }}
            heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
            heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
            dockerfile_directory: ./
            dockerfile_name: Dockerfile
            docker_options: "--no-cache"
            process_type: web
